"""life insurance schema extension

Revision ID: 81ba5eebd41d
Revises: 
Create Date: 2026-07-28 20:38:25.364354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '81ba5eebd41d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurer',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('website_root', sa.String(length=255), nullable=False),
    sa.Column('crawl_policy_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('occupation_category',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('insurer_id', app.db.models.GUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('insurer_label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('insurer_id', app.db.models.GUID(), nullable=False),
    sa.Column('vertical', sa.String(length=40), nullable=False),
    sa.Column('product_type', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['insurer_id'], ['insurer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_version',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('product_id', app.db.models.GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibility_rule',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('policy_version_id', app.db.models.GUID(), nullable=False),
    sa.Column('occupation_category_id', app.db.models.GUID(), nullable=True),
    sa.Column('smoker_status', sa.String(length=20), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=False),
    sa.Column('age_max', sa.Integer(), nullable=False),
    sa.Column('restriction_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('document_id', app.db.models.GUID(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('paragraph_ref', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['occupation_category_id'], ['occupation_category.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graded_fact',
    sa.Column('id', app.db.models.GUID(), nullable=False),
    sa.Column('policy_version_id', app.db.models.GUID(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('document_id', app.db.models.GUID(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('paragraph_ref', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graded_fact')
    op.drop_table('eligibility_rule')
    op.drop_table('policy_version')
    op.drop_table('product')
    op.drop_table('occupation_category')
    op.drop_table('insurer')
    # ### end Alembic commands ###
